language: objective-c
osx_image: xcode7.1

install:
  - make travis-get-deps

before_script:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - bundle exec fastlane verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
