language: objective-c
osx_image: xcode7.1
install:
  - make travis-get-deps
script: bundle exec fastlane verify
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
