language: objective-c
osx_image: xcode7.1
env:
  matrix:
    - FL_ARGS="verify"
    - FL_ARGS="verify scheme:WikipediaArabic"
    - FL_ARGS="verify os:8.4"

install:
  - make travis-get-deps

before_script:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6 (9.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")

script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - bundle exec fastlane $FL_ARGS

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - tail -n 500 ./build/xcodebuild.og

branches:
  only:
    - master
